# Generated by Django 6.0.3 on 2026-04-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('block', 'Блок'), ('tool', 'Инструмент'), ('weapon', 'Оружие'), ('armor', 'Броня'), ('food', 'Еда'), ('material', 'Материал'), ('redstone', 'Редстоун'), ('potion', 'Зелье')], max_length=20)),
                ('stack_size', models.IntegerField(default=64)),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('epic', 'Эпический')], default='common', max_length=10)),
                ('is_removed', models.BooleanField(default=False)),
                ('added_in_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_added', to='versions.minecraftversion')),
                ('versions', models.ManyToManyField(related_name='items', to='versions.minecraftversion')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
