# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Шаг механики',
                'verbose_name_plural': 'Шаги механики',
                'ordering': ['step_number'],
            },
        ),
    ]
