# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanic_steps', '0001_initial'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicstep',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mechanics.mechanic'),
        ),
        migrations.AlterUniqueTogether(
            name='mechanicstep',
            unique_together={('mechanic', 'step_number')},
        ),
    ]
