# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biomes', '0001_initial'),
        ('dimensions', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('common', 'Обычная'), ('uncommon', 'Необычная'), ('rare', 'Редкая'), ('epic', 'Эпическая')], max_length=10)),
                ('description', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('biomes', models.ManyToManyField(related_name='structures', to='biomes.biome')),
                ('dimensions', models.ManyToManyField(related_name='structures', to='dimensions.dimension')),
                ('versions', models.ManyToManyField(related_name='structures', to='versions.minecraftversion')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структуры',
            },
        ),
    ]
