# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biomes', '0001_initial'),
        ('dimensions', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('health', models.FloatField()),
                ('damage', models.FloatField(default=0)),
                ('behavior', models.CharField(choices=[('passive', 'Пассивный'), ('neutral', 'Нейтральный'), ('hostile', 'Враждебный'), ('boss', 'Босс'), ('tameable', 'Приручаемый')], max_length=20)),
                ('category', models.CharField(choices=[('animal', 'Животное'), ('monster', 'Монстр'), ('ambient', 'Окружение'), ('aquatic', 'Водный'), ('villager', 'Житель'), ('undead', 'Нежить'), ('arthropod', 'Членистоногое'), ('illager', 'Разбойник')], max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('icon_path', models.CharField(blank=True, max_length=200)),
                ('light_level', models.IntegerField(blank=True, null=True)),
                ('biomes', models.ManyToManyField(related_name='mobs', to='biomes.biome')),
                ('spawns_in', models.ManyToManyField(related_name='mobs', to='dimensions.dimension')),
                ('versions', models.ManyToManyField(related_name='mobs', to='versions.minecraftversion')),
            ],
            options={
                'verbose_name': 'Моб',
                'verbose_name_plural': 'Мобы',
            },
        ),
    ]
