# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('redstone', 'Редстоун'), ('farming', 'Фермерство'), ('breeding', 'Разведение'), ('enchanting', 'Зачарование'), ('brewing', 'Зельеварение'), ('transport', 'Транспорт'), ('storage', 'Хранение')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Новичок'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], max_length=12)),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('estimated_time', models.IntegerField(default=10)),
                ('versions', models.ManyToManyField(related_name='mechanics', to='versions.minecraftversion')),
            ],
            options={
                'verbose_name': 'Механика',
                'verbose_name_plural': 'Механики',
            },
        ),
    ]
