# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('completed_tutorials', '0001_initial'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtutorial',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanics.mechanic'),
        ),
    ]
