# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.IntegerField(default=1)),
                ('max_count', models.IntegerField(default=1)),
                ('chance', models.FloatField(default=1.0)),
                ('is_rare', models.BooleanField(default=False)),
                ('looting_multiplier', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_by', to='items.item')),
            ],
            options={
                'verbose_name': 'Выпадение лута',
                'verbose_name_plural': 'Выпадения лута',
            },
        ),
    ]
