# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loot_drops', '0001_initial'),
        ('mobs', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootdrop',
            name='mob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='mobs.mob'),
        ),
        migrations.AddField(
            model_name='lootdrop',
            name='versions',
            field=models.ManyToManyField(related_name='loot_drops', to='versions.minecraftversion'),
        ),
    ]
