# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biomes', '0001_initial'),
        ('dimensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobSpawnCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_y', models.IntegerField(blank=True, null=True)),
                ('max_y', models.IntegerField(blank=True, null=True)),
                ('light_level_max', models.IntegerField(default=7)),
                ('only_at_night', models.BooleanField(default=False)),
                ('biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biomes.biome')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimensions.dimension')),
            ],
            options={
                'verbose_name': 'Условие спавна',
                'verbose_name_plural': 'Условия спавна',
            },
        ),
    ]
