# Generated by Django 6.0.3 on 2026-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateField()),
                ('is_latest', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Версия Minecraft',
                'verbose_name_plural': 'Версии Minecraft',
                'ordering': ['-release_date'],
            },
        ),
    ]
