# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructureChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_description', models.CharField(blank=True, max_length=200)),
                ('average_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Сундук структуры',
                'verbose_name_plural': 'Сундуки структур',
            },
        ),
    ]
