# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure_chests', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurechest',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests', to='structures.structure'),
        ),
    ]
