# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_count', models.IntegerField(default=1)),
                ('recipe_type', models.CharField(choices=[('crafting_2x2', 'Верстак 2x2'), ('crafting_3x3', 'Верстак 3x3'), ('smelting', 'Печь'), ('blasting', 'Плавильная печь'), ('smoking', 'Коптильня'), ('campfire', 'Костёр'), ('smithing', 'Кузнечный стол'), ('stonecutting', 'Камнерез'), ('brewing', 'Варочная стойка')], max_length=20)),
                ('shape', models.JSONField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('result_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='items.item')),
                ('versions', models.ManyToManyField(related_name='recipes', to='versions.minecraftversion')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
