# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_history', '0001_initial'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='user_profiles.userprofile'),
        ),
    ]
