# Generated by Django 6.0.3 on 2026-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChestLootItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.IntegerField()),
                ('max_count', models.IntegerField()),
                ('chance', models.FloatField()),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Лут сундука',
                'verbose_name_plural': 'Луты сундуков',
            },
        ),
    ]
