# Generated by Django 6.0.3 on 2026-04-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chest_loots', '0001_initial'),
        ('items', '0001_initial'),
        ('structure_chests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestlootitem',
            name='chest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='structure_chests.structurechest'),
        ),
        migrations.AddField(
            model_name='chestlootitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
