# Generated by Django 6.0.3 on 2026-04-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('temperature', models.FloatField(default=0.5)),
                ('description', models.TextField(blank=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomes', to='dimensions.dimension')),
            ],
            options={
                'verbose_name': 'Биом',
                'verbose_name_plural': 'Биомы',
            },
        ),
    ]
